### ISSUE TITLE
A problem with new lines

### ISSUE THREAD

**Issue by kasperosterbye** [pillar-markup/BeautifulComments#27]
@estebanlm brought up an issue with newlines in a conversation we had:
<img width="410" alt="image" src="https://user-images.githubusercontent.com/17723745/152632476-ccf74406-c5ea-476b-8987-cb9405d261f0.png"> 
which should have been:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/17723745/152632508-07caf069-6ab4-4ebd-915c-eae9ca42b5f8.png">

A PR will arrive shortly to fix the issue, I just like to have issues for my PRs

**Comment by estebanlm** [comment]
Hi, 
It shoul *have not* been like the second example. Second example has an error too (an extra cr).
Taken from P9, this is how it should look:

![image](https://user-images.githubusercontent.com/513630/152675221-95e274d7-da68-48d7-8de3-92f42dd6798f.png)

**Comment by kasperosterbye** [comment]
😉 - that is how it ended up being in the code I pushed - at least in the version which runs on my machine
<img width="352" alt="image" src="https://user-images.githubusercontent.com/17723745/152675791-dd65e1ef-2c46-4d38-9fb7-4bc5591b9ad5.png">

Why one want that in the comment in the browser when you have that information in both uml and class view is an other matter.

**Comment by estebanlm** [comment]
because :
1. we can :)
2. IMO the UML view is useless because I want to show a view of the class in the context (and yes, UML view could work but this is not the case because I cannot get a real idea when the UML view as it is. 
3. The class view does not helps either, since classes in the same hierarchy can be in different packages, etc.
4. Most important than that, I want to show all the relevant information in a single point, not force an user to jump from comment, to uml tab, to hierarchy view in the browser, etc...
5. Finally, I want to use this to also generate some html static documentation, and I want one and the other to look as close as possible.

**Comment by kasperosterbye** [comment]
Wonderful arguments all of them. It seems like the in-image documentation and its tools will change in quality over the years to come.
